import type { Intent } from './classifier';

const responseVariants: Record<Intent, string[]> = {
  greeting: [
  "Hey, good to see you! I'm Athena — I help Filipinos figure out if something online is sketchy, walk through scam recovery, and connect you with the right authorities. What's on your mind today?",
  "Hi there! I'm Athena. Whether you got a weird text, you're worried about an account, or something just feels off — I can help. What's going on?",
  "Kumusta! I'm Athena, your cybersecurity buddy. Got a suspicious message, an account concern, or just curious about staying safe online? Tell me what's up."],

  thanks: [
  "Anytime — really glad I could help. Stay sharp out there, and don't hesitate to come back if something else feels off. 🙌",
  "You're welcome! Honestly, the fact that you're double-checking is half the battle. I'm here whenever you need me.",
  'Walang anuman! Just remember — if something ever feels rushed or too good to be true, it usually is. Take care.'],

  capabilities: [
  'Good question! Think of me as your cybersecurity sidekick. I can help you spot scam texts and emails, evaluate suspicious links, walk you through securing GCash or Facebook, and point you to the right people — PNP-ACG, NBI, DICT, NPC — when you need to report something. Everything I tell you comes from verified Philippine advisories. So… what would you like to start with?',
  "Happy to explain! I help with three main things: figuring out if a message, link, or call is a scam; walking you through what to do if you've already been targeted; and connecting you to the right authority for reporting. I won't pretend to know everything, but for Philippine cybercrime stuff, I've got you covered."],

  emergency: [
  "Okay, deep breath — I've got you. If money already moved or your account is compromised, time matters a lot. Do this in order, right now:\n\n1. Stop the bleeding.\n   • Cut off all contact with the scammer. No more replies, no more clicks.\n   • If you shared an OTP, MPIN, or password, change it immediately on every account that uses it.\n   • Log out of all sessions in your banking app (most have a \"sign out everywhere\" option).\n\n2. Call your bank or e-wallet's fraud hotline. The first 60 minutes are critical.\n   • BPI — (02) 8889-10000\n   • BDO — (02) 8631-8000\n   • Metrobank — (02) 8870-0700\n   • Landbank — (02) 8405-7000\n   • GCash — 2882 (toll-free from Globe/TM)\n   • Maya — (02) 8845-7788\n   Tell them: \"I'm a fraud victim — please freeze my account.\" Ask them to reverse the transaction if it's still pending. Under BSP Circular 1140, they must act on fraud reports within 24 hours.\n\n3. Preserve evidence.\n   Screenshot everything — the message, the link, the transaction receipt, the scammer's number or email. Email it to yourself so it's backed up.\n\n4. Report to authorities.\n   • PNP Anti-Cybercrime Group (24/7) — acg.pnp.gov.ph or (02) 8723-0401 local 7491\n   • RACU 13 Caraga — 0946-326-7938\n   • Surigao del Sur PPO — 0998-598-7356\n   • DICT online-scam hotline — 1326\n   • NBI Cybercrime Division — (02) 8523-8231\n   Bring screenshots, transaction records, and a valid government ID when you file.\n\n5. If your identity or banking details were exposed.\n   File a complaint with the National Privacy Commission at privacy.gov.ph under RA 10173.\n\nCan you tell me what platform was used (GCash, BPI, etc.) and how much was taken? I can give you tailored next steps.",
  "Stay with me — we'll handle this step by step. Here's the urgent playbook:\n\n1. Right now (next 5 minutes).\n   • Don't reply to the scammer again. Don't click anything else.\n   • Change your bank/e-wallet password and MPIN if you shared them.\n   • Sign out of all active sessions in your banking app.\n\n2. Within the next hour — call your bank or wallet fraud line.\n   • GCash — 2882\n   • Maya — (02) 8845-7788\n   • BPI — (02) 8889-10000\n   • BDO — (02) 8631-8000\n   • Metrobank — (02) 8870-0700\n   Tell them: \"I'm a fraud victim — please freeze my account.\" If the transfer is still pending, they may be able to reverse it.\n\n3. Preserve evidence.\n   Screenshot the whole conversation, the link you clicked, transaction receipts, and the scammer's number or email. Email it to yourself so it's backed up.\n\n4. File a report.\n   • PNP-ACG (24/7) — acg.pnp.gov.ph or (02) 8723-0401 local 7491\n   • RACU 13 Caraga — 0946-326-7938\n   • Tandag CPS — 0998-598-7378\n   • Bislig CPS — 0998-598-7359\n   • DICT online-scam hotline — 1326\n   Bring screenshots, proof of transfer, and a valid government ID.\n\nTo help you prioritize — what bank or wallet was hit, and roughly how much was taken? I can sharpen the next steps based on that."],

  otp: [
  "Okay, super important rule: never share your OTP or MPIN with anyone. Not even someone who says they're from your bank, GCash, or 'PNP'. Real institutions will never ask for these — that's not how their systems work.\n\nIf you already shared one though, don't panic, but move fast:\n• Change your MPIN and password right now\n• Call the platform's fraud hotline (GCash 2882, your bank's 24/7 line)\n• Report it to PNP-ACG at (02) 8723-0401 local 7491\n\nUnder BSP Circular 1140, banks have to act on fraud reports within 24 hours, so the sooner you call, the better. Did you already share one, or is someone asking for it now?",
  "Great that you're asking before sharing — that's already the right instinct. The rule is simple: OTPs and MPINs are like the keys to your house. No legit company, no government agency, nobody should ever need them from you. If anyone asks, it's a scam, full stop.\n\nIf you've already given one out, change your MPIN immediately and call your bank or e-wallet's fraud line right away. Want me to walk you through what to do next?"],

  gcash: [
  "Smart move thinking about this proactively! Here's the short version for locking down GCash or Maya:\n\nTurn on biometric login (fingerprint or face) in the app settings — that's your first line of defense. Set an MPIN you don't use anywhere else, and enable transaction notifications so you'll know the instant anything moves. Never screenshot or share your QR code, and only top up through the official app.\n\nAnd the big one: if anyone — and I mean anyone — asks for your OTP or MPIN, that's a scam. Block and report.\n\nIf you think your account might already be compromised, call GCash 2882 or Maya (02) 8845-7788 right away to freeze it. Want me to walk you through any of these steps?",
  "Good thinking. Here's what actually moves the needle for GCash/Maya security:\n\nThe single most important thing is enabling biometric login — that alone stops most opportunistic attacks. After that, use a unique MPIN (not the same as your other PINs), turn on transaction alerts, and never share your OTP, even if the person sounds super convincing.\n\nIs your account safe right now, or are you worried something already happened?"],

  sms_scam: [
  "Yeah, that sounds suspicious — and you're right to double-check. These messages (we call them 'smishing') are designed to panic you into clicking before thinking. Some classic signs:\n\nThey create urgency ('your account will be locked in 24 hours'), use shortened or weird-looking links, or claim you've won something. Real banks and agencies don't send links via SMS asking you to 'verify' or 'update' anything.\n\nHere's what to do: don't click, don't reply. Forward the message to 7726 (works for both Globe and Smart) — that helps them block the sender. Then you can report to PNP-ACG at (02) 8723-0401 local 7491.\n\nWant to share what the message says? I can help you spot exactly what's off.",
  "Good instinct to pause on that. Scam texts in the Philippines have gotten really good — they mimic banks, GCash, even courier services. A few quick checks: Does the link look like the official domain, or just close to it? Is the message trying to rush you? Did you actually transact with that company recently?\n\nWhatever you do, don't tap the link. Forward the SMS to 7726 (your telco will investigate), and if you want, paste me the message and I'll walk through it with you."],

  phishing_email: [
  "Phishing emails are tricky because they can look really legit at first glance. Here's how I'd approach yours:\n\nStart with the sender's full email address (not just the name) — scammers love near-misses like 'bdo-secure@gmial.com' instead of the real domain. Then look at how it greets you — 'Dear Customer' instead of your actual name is a red flag. Check if it's pushing urgency, and hover (don't click) any links to see where they actually go.\n\nIf anything feels off, just go to the company's site directly by typing the address yourself. And you can forward suspicious emails to report@cert.gov.ph — DICT actually investigates these.\n\nWant to tell me more about the email? I can help you decide if it's safe to act on.",
  "Good call checking first. Phishing emails almost always have at least one tell — you just have to know where to look. Sender address (look for misspelled domains), generic greetings, urgent threats, and links that don't match the real company's domain are the big four.\n\nWhen in doubt: don't click anything in the email. Open a new tab and go to the official site yourself. Want to describe what the email says? I can help you decide."],

  link_check: [
  "So here's the honest truth — I can't actually open the link myself. But I can teach you how to size it up in under a minute.\n\nFirst, really look at the domain. Scammers love near-lookalikes ('bdo-online.com.ph' vs the real 'bdo.com.ph'). Watch for typos and extra words. Second, you can paste the URL into virustotal.com — it's free and runs the link past dozens of security scanners. And if it's a shortened link (bit.ly, tinyurl), expand it first at unshorten.it before clicking.\n\nMy general rule: if you're unsure, don't click. Just type the official site into your browser yourself.\n\nWant to share the link? I can tell you what to specifically look for.",
  "I get this one a lot — and unfortunately I can't open links directly. But here's the trick: most scam URLs give themselves away if you look closely. Compare the domain character-by-character to the real one (scammers swap 'o' for '0', add hyphens, etc.). Run it through virustotal.com for a second opinion. And if it's shortened, expand it first.\n\nIf you paste me the URL or describe what you see, I can flag any patterns I recognize."],

  investment_scam: [
  "Okay, this is one of the most common — and most devastating — scams hitting Filipinos right now. So let me cut through the noise.\n\nThe single biggest red flag is anyone promising guaranteed returns. Real investments fluctuate. If someone says '5% daily' or 'double in 15 days', it's a scam. Period. Other warning signs: they push you to recruit others, they're not registered with SEC, they use celebrity endorsements (often fake), or they suddenly charge 'release fees' when you try to withdraw.\n\nBefore you put in a single peso, check sec.gov.ph to see if the company has a Secondary License. A business permit isn't enough — soliciting investments requires that specific license.\n\nIf you've already invested or you suspect a scheme, report it to the SEC at epd@sec.gov.ph or (02) 8818-5476. Are you trying to evaluate a specific opportunity, or has something already happened?",
  "Tough one, because these scams are really polished now — they have fake testimonials, slick apps, even legit-looking dashboards. But here's the thing: every single one of them eventually does one of three things — blocks withdrawals, charges 'release fees', or just disappears.\n\nThe golden rule: if returns are guaranteed, it's not an investment, it's bait. Always verify the company has an SEC Secondary License at sec.gov.ph before sending money.\n\nWhat's the situation — checking one out, or already in?"],

  job_scam: [
  "Job scams have exploded recently, especially the 'task' ones on Telegram and WhatsApp where they pay you a small amount first to build trust, then ask for a 'deposit' for bigger tasks. Once you pay, they vanish.\n\nThings I'd look out for: any upfront fee (training, registration, deposit), recruitment via random SMS or Telegram, vague company info, unrealistic earnings (₱5,000/day for liking videos isn't real), and pressure to recruit friends.\n\nLegit employers don't ask you to pay them to work. You can verify a company through DOLE at dole.gov.ph or check business registration with DTI. If you've already been scammed, report it to PNP-ACG at (02) 8723-0401 local 7491.\n\nWhat's the offer look like? I can help you spot the red flags.",
  "Yeah, these are everywhere now. The 'task' scam pattern is especially nasty — they pay you a little at first so you trust them, then bait you into 'investing' to unlock bigger tasks, and once you pay, poof.\n\nQuick filter: any legitimate job has zero upfront cost to you. The moment they ask for a fee, training payment, or 'deposit', walk away. Want to tell me what the job is and how they reached out? I'll help you read it."],

  identity_theft: [
  "That's really stressful — I'm sorry you're dealing with this. Let's get on top of it fast:\n\nStart by changing your email password (that's the master key — everything else resets from there), then move to banking, then social media. Turn on 2FA on every account, ideally with an authenticator app rather than SMS. Call your bank and e-wallet providers to flag fraudulent activity and freeze cards if needed.\n\nThen file a report with PNP-ACG at (02) 8723-0401 local 7491 — bring screenshots and a valid ID. If your personal data was leaked or misused, you can also file with the National Privacy Commission at privacy.gov.ph under RA 10173.\n\nDo you know how they got access — was it a phishing link, a leaked password, or something else? I can help you close the gap.",
  "Okay, this is fixable, but we need to move fast. The most important account to lock down first is your email — because if they have that, they can reset everything else. Change that password right now, enable 2FA, and check 'Where you're logged in' for unfamiliar sessions.\n\nThen call your bank and e-wallet support to flag activity. Then report to PNP-ACG ((02) 8723-0401 local 7491) so there's a paper trail. Walk me through what happened?"],

  account_security: [
  "Honestly? The whole thing comes down to four habits, and once you have them, you're way ahead of most people:\n\nFirst, use unique passwords for every account — get a password manager (Bitwarden is free and great) so you don't have to remember them all. Second, turn on 2FA everywhere, preferably with an authenticator app like Google Authenticator rather than SMS. Third, slow down before clicking — most breaches happen because someone clicked a link in a panic. And fourth, keep your phone and apps updated — half of malware exploits outdated software.\n\nWhich of these would you like to dig into? Setting up a password manager or 2FA are usually the most impactful first moves.",
  "Great that you're thinking about this before something goes wrong. Real talk — you don't need to be paranoid, you just need a few solid habits. Use a password manager, enable 2FA (authenticator app, not SMS), pause before clicking anything urgent, and keep your software updated. That's 90% of personal cybersecurity.\n\nWant me to walk you through any of them? Most people skip 2FA because it sounds technical, but it's genuinely a 5-minute thing."],

  report_scam: [
  "Glad you want to report — that's actually huge, because most scams go unreported and the scammers keep running the same playbook on others. Here's where to file, depending on the case:\n\nFor most online scams, your main channel is the PNP Anti-Cybercrime Group at (02) 8723-0401 local 7491, or their online complaint form at acg.pnp.gov.ph. If it's a more complex or cross-border case, NBI Cybercrime Division handles those at (02) 8523-8231. For phishing emails specifically, forward to report@cert.gov.ph.\n\nBefore you file, gather: screenshots of the scam, transaction records, the sender's number or email, and bring your government-issued ID. If you're in Surigao del Sur, you can also file in person at Tandag City Police Station at 0998-598-7314.\n\nWhat kind of scam are you reporting? I can point you to the most useful channel.",
  "Reporting actually matters more than people realize — every report helps authorities build cases and shut these operations down. The main channel for most cases is PNP-ACG ((02) 8723-0401 local 7491 or acg.pnp.gov.ph). For phishing emails, CERT-PH at report@cert.gov.ph. For bigger or cross-border stuff, NBI Cybercrime at (02) 8523-8231.\n\nBring screenshots, transaction proof, and a valid ID. What happened? I'll help you pick the right one."],

  general_scam: [
  'Good instinct to check — that pause-and-verify habit is what keeps people safe. Without seeing the specifics, here\'s the universal scam-detection checklist:\n\n• Urgency ("act in 24 hours or your account is locked") → almost always a red flag\n• Requests for OTP, MPIN, password, or banking details → never legitimate, full stop\n• Promises of guaranteed money, prizes, or returns → if it sounds too good, it is\n• Generic greetings ("Dear Customer") or weird sender addresses → impersonation\n• Pressure to keep it secret or move to a private chat → classic isolation tactic\n\nIf you want me to look at something specific — paste the message, link, or describe the situation — I can tell you exactly which red flags are showing up. What did you receive?',
  'Smart that you\'re double-checking. Most scams in the Philippines fall into a few patterns: fake bank/GCash texts, fake job offers (especially "task" jobs on Telegram), investment-doubling schemes, and impersonation of relatives or government agencies.\n\nThe single best filter? Three questions:\n1. Are they rushing you?\n2. Are they asking for an OTP, MPIN, password, or money?\n3. Did you reach out to them first, or did they reach out to you?\n\nIf any answer worries you, treat it as a scam until proven otherwise. Want to tell me what you\'re looking at? I can break down the specific signs.'],

  what_is: [
  "Happy to explain — but to give you something useful, I need a bit more context. Are you asking about:\n\n• A specific scam type (phishing, smishing, vishing, romance scam, investment scam)?\n• A security concept (2FA, OTP, MPIN, password manager)?\n• A platform or app (GCash, Maya, Facebook, Gmail)?\n• A Philippine authority (PNP-ACG, NBI, DICT, NPC)?\n\nDrop the term you want to understand and I'll break it down with a Philippine-specific example so it actually sticks.",
  'Good question! I can explain pretty much any cybersecurity term, scam pattern, or Philippine cybercrime concept. Just tell me what you\'re curious about — "what is phishing", "how does 2FA work", "what\'s an OTP for", that kind of thing. I\'ll keep it short and practical, with examples that actually apply here.'],

  fallback: [
  "I want to help, but I'm not totally sure I caught what you're dealing with. Could you tell me a bit more? Like — did you get a weird message, are you worried about an account, did you click something you shouldn't have? The more you share, the more useful I can be.",
  "Hmm, I'm not 100% sure what direction to take this. Walk me through it a little — is this about a suspicious text, an account issue, money already lost, or something else? I'll meet you where you are.",
  "Tell me a bit more so I can actually be helpful. Are we talking about a specific message or link you got, an account that feels compromised, or just general 'how do I stay safe' kind of stuff? Any of those is totally fine — I just need a starting point."]

};
// ───── Tagalog response variants ─────
// Top intents are translated. Others fall back to English.
const responseVariantsTL: Partial<Record<Intent, string[]>> = {
  greeting: [
  'Kumusta! Ako si Athena — tutulungan kitang suriin kung scam ang isang mensahe, link, o tawag, at ituturo ko sa iyo kung saan magrereport. Anong kailangan mo ngayon?',
  'Hi! Si Athena ito. Kung may natanggap kang kahina-hinalang text, naloko ka, o gusto mo lang malaman kung paano protektahan ang account mo — kaya kong tulungan. Anong nangyari?',
  'Kamusta! Ako si Athena. Para sa mga concerns tungkol sa scam, hacked na account, o cybercrime sa Pilipinas — nandito ako. Pakikuwento mo lang ang sitwasyon mo.'],

  thanks: [
  'Walang problema. Ingat ka palagi, at bumalik ka lang kung may iba pang gusto mong itanong.',
  'Sige, mabuti naman at nakatulong. Mag-iingat ka sa mga kahina-hinalang mensahe.',
  'Wala iyon. Kung may makita kang kahina-hinala ulit, sabihan mo lang ako.'],

  capabilities: [
  'Tutulungan kitang malaman kung scam ang isang text, email, tawag, o link. Pwede rin akong gumabay kung paano i-secure ang GCash, Maya, o bank account mo. At kung naloko ka na, sasamahan kita sa proseso ng pag-uulat sa PNP-ACG, NBI, o DICT. Saan mo gustong magsimula?',
  "Tatlong bagay ang kaya kong tulungan: una, suriin kung scam ang isang bagay; ikalawa, gabayan ka kung ano ang gagawin kapag naloko ka; at ikatlo, ituro sa'yo ang tamang authority na pagsusumbungan. Ano'ng pinakaurgent ngayon?"],

  emergency: [
  'Pasensya na sa nangyari. Ito ang dapat gawin ngayon, sunud-sunod:\n\n1. Itigil agad ang pakikipag-ugnayan sa scammer. Huwag nang mag-click ng kahit ano pa nila ipadala.\n\n2. Tawagan ang fraud hotline ng bangko o e-wallet mo agad — bawat minuto ay mahalaga:\n   • GCash — 2882\n   • Maya — (02) 8845-7788\n   • BPI — (02) 8889-10000\n   • BDO — (02) 8631-8000\n   • Metrobank — (02) 8870-0700\n   Sabihin mo: "Biktima ako ng fraud. Pakitulungan akong i-freeze ang account at i-reverse ang transaction." Sa ilalim ng BSP Circular 1140, dapat silang tumugon sa loob ng 24 oras.\n\n3. Mag-screenshot ng lahat — usap kayo, link, resibo, numero ng scammer. I-email mo sa sarili mo para may backup.\n\n4. Magsumbong sa awtoridad:\n   • PNP Anti-Cybercrime Group — acg.pnp.gov.ph o (02) 8723-0401 local 7491\n   • RACU 13 Caraga — 0946-326-7938\n   • DICT hotline — 1326\n   • Tandag CPS — 0998-598-7378  |  Bislig CPS — 0998-598-7359\n\nMagdala ng screenshots, transaction records, at valid ID kapag magfafile ka. Anong platform ang nasalanta at magkano ang nawala? Para mabigyan kita ng mas tamang advice.'],

  otp: [
  'Importanteng tandaan: huwag mong ibibigay ang OTP o MPIN mo sa kahit kanino — kahit pa nagpapakilala silang taga-bangko, GCash, o PNP. Hindi talaga humihingi ng OTP ang mga lehitimong institusyon.\n\nKung naibigay mo na, gawin agad:\n• Palitan ang MPIN at password mo ngayon din\n• Tawagan ang fraud hotline (GCash 2882, o bangko mo)\n• Magreport sa PNP-ACG sa (02) 8723-0401 local 7491\n\nNaibigay mo na ba, o may humihingi pa lang ngayon?',
  'Tama na nagtatanong ka muna. Ang OTP at MPIN ay parang susi ng bahay mo — walang lehitimong kompanya ang dapat humihingi nito. Kung may humihingi, scam yan.\n\nNaibigay mo na ba, o may humihingi pa lang ngayon?'],

  gcash: [
  'Magandang isipin to nang maaga. Ito ang mahalaga para sa GCash o Maya security:\n\nI-on mo ang biometric login (fingerprint o face) sa app settings — yan ang unang depensa mo. Gumamit ng MPIN na hindi mo ginagamit sa ibang account, at i-enable ang transaction notifications para alam mo kaagad kung may galaw. Huwag i-screenshot o i-share ang QR code mo.\n\nAt ang pinakaimportante: kung may humihingi ng OTP o MPIN, scam yun, walang exception.\n\nKung nag-aalala kang nakompromiso na ang account mo, tawagan agad ang GCash sa 2882 o Maya sa (02) 8845-7788 para ma-freeze. May konkretong nangyari na ba, o gusto mo lang i-secure pa?',
  'Para maging safe ang GCash o Maya mo: huwag ibigay ang MPIN o OTP kahit kanino. I-on ang fingerprint login. Kung may tumawag na nagpapanggap na taga-GCash at humihingi ng code, ibaba agad ang telepono. Ligtas ba ang account mo ngayon?',
  'Tatlong rule sa GCash: 1. Secret ang MPIN at OTP. 2. Huwag i-click ang links sa text. 3. I-on ang biometrics. Kung feeling mo na-hack ka, tawag agad sa 2882 para i-block ang account.'],

  sms_scam: [
  'Tama lang mag-pause ka muna. Ang mga scam SMS sa Pilipinas ay ginawa para magulat at mag-click ka nang hindi nag-iisip. Mga senyales:\n\n• Pinangangailangan ka (24 hours, ma-lock na account, atbp.)\n• May maikling o kakaibang link\n• Premyo na hindi mo naman pinaglaban\n• Pakikiusap para ipadala ang OTP\n\nAng tamang gawin: huwag mag-click, huwag sumagot. I-forward ang text sa 7726 para ma-block ng telco ang sender. Pwede ka ring magreport sa PNP-ACG sa acg.pnp.gov.ph.\n\nIpaste mo nga ang text dito? Pwede kong i-check kung anong red flags andoon.',
  'Mabuti at nagduda ka. Ang mga text scam ngayon ay nagpapanggap na bangko o courier. Huwag mong i-click ang link. I-forward sa 7726 para ma-report sa telco. Gusto mo bang i-paste dito ang text para masuri natin?',
  'Huwag mag-panic. Kung may link yung text at nagmamadali sila, 99% scam yan. Huwag mag-reply. I-paste mo dito yung mensahe at titingnan ko kung anong klase ng scam yan.'],

  link_check: [
  'Hindi ko mabubuksan mismo ang link, pero ituturo ko sa\'yo kung paano i-evaluate sa loob ng isang minuto:\n\nUna, basahin mo ng maigi ang domain. Madalas ginagaya lang ng scammers — "bdo-online.com.ph" kunyari, sa halip na totoong "bdo.com.ph". Pansinin ang typo o sobrang gitling.\n\nIkalawa, i-paste mo ang URL sa virustotal.com — libre yun at sa-scan ng dozens of security engines.\n\nIkatlo, kung shortened (bit.ly, tinyurl), i-expand muna sa unshorten.it bago mag-click.\n\nKung di ka sure, huwag mag-click. I-type mo sa browser mismo ang opisyal na website. Pasend mo nga ang link?',
  'Para malaman kung safe ang link: tingnan maigi ang spelling ng website. Madalas may maliit na typo ang mga scam sites. Pwede mo ring i-paste dito ang link at susuriin ko ang pattern nito.',
  'Huwag i-click agad! I-paste mo muna dito ang link. Titingnan ko kung gumagamit ito ng mga kilalang panlilinlang tulad ng maling spelling o kahina-hinalang format.'],

  general_scam: [
  'Tama lang na nagva-verify ka. Ito ang universal scam-detection checklist:\n\n• Nagmamadali — "act in 24 hours or your account is locked" → red flag\n• Humihingi ng OTP, MPIN, password, o banking details → never lehitimo\n• Garantisadong kita o premyo → kung "too good to be true", scam yun\n• "Dear Customer" o kakaibang sender → impersonation\n• Pakikiusap na ilihim o lipat sa private chat → classic isolation tactic\n\nKung may specific na mensahe ka, ipakita mo — pwede kong i-check kung anong red flags andoon.'],

  account_security: [
  "May apat na ugali na malakas magprotekta:\n\n1. Iba't ibang password sa bawat account. Gumamit ka ng password manager (libre ang Bitwarden) para hindi mo kailangan tandaan lahat.\n2. I-on ang 2FA (two-factor authentication) sa lahat — mas mabuti ang authenticator app (Google Authenticator) kaysa SMS.\n3. Hinay-hinay sa pag-click. Halos lahat ng breach ay nag-uumpisa sa rushed click sa link.\n4. I-update ang phone at apps mo. Maraming malware ang umaatake sa lumang software.\n\nAlin sa apat ang gusto mong unahin? Karaniwang 2FA o password manager ang pinakamalaki ang impact."],

  what_is: [
  'Sige, masaya akong ipaliwanag — pero kailangan ko ng konting context. Ano ang gusto mong intindihin:\n\n• Isang uri ng scam (phishing, smishing, vishing, romance scam, investment scam)?\n• Isang security concept (2FA, OTP, MPIN, password manager)?\n• Isang platform o app (GCash, Maya, Facebook, Gmail)?\n• Isang authority sa Pilipinas (PNP-ACG, NBI, DICT, NPC)?\n\nIsulat mo lang yung term at ipapaliwanag ko nang malinaw at may halimbawa para sa Pilipinas.'],

  report_scam: [
  'Mabuti na nagrereport ka — madalas hindi nire-report ang scams kaya patuloy ang scammers. Ito ang dapat lapitan, depende sa kaso:\n\nPara sa karamihan ng online scams: PNP Anti-Cybercrime Group — acg.pnp.gov.ph o (02) 8723-0401 local 7491 (24/7). Para sa mas komplikado o cross-border na kaso: NBI Cybercrime Division — (02) 8523-8231. Para sa phishing email: forward sa report@cert.gov.ph.\n\nMaghanda ng: screenshots, transaction records, numero o email ng sender, at valid ID. Kung nasa Surigao del Sur ka, pwede ka rin pumunta sa Tandag City Police Station (0998-598-7378) o Bislig CPS (0998-598-7359).\n\nAnong klase ng scam? Pwede kitang ituro sa pinakatamang channel.'],

  fallback: [
  'Gusto kitang tulungan, pero hindi ko gaanong nakuha kung ano ang problema. Pakikuwento mo nga ng kaunti — may natanggap ka bang kahina-hinalang mensahe, may nakukulang ba sa account mo, o may pinindot kang link na hindi mo dapat pinindot?',
  "Kailangan ko ng konting detalye para makatulong. Tungkol ba ito sa kahina-hinalang text, sira o nakawang account, o nawawalang pera? Kahit alin sa mga'yan, ok lang — kailangan ko lang ng simulan."],

  investment_scam: [
  'Investment scams ay laganap ngayon. Pinakamalaking red flag: kung "guaranteed returns" o "double in X days" — scam yan, walang exception. Lumilipad ang totoong investments, hindi yan tinitiyak.\n\nIba pang senyales: pinipilit kang mag-recruit ng iba, walang SEC license, gumagamit ng pekeng celebrity endorsements, biglang may "release fee" kapag mag-wiwithdraw ka.\n\nBago magpadala ng kahit isang piso, i-verify ang kompanya sa sec.gov.ph — kailangan may Secondary License sila (hindi sapat ang business permit). Kung naloko ka na o suspicious ka sa scheme, mag-report sa SEC — epd@sec.gov.ph o (02) 8818-5476.\n\nNag-iimbestiga ka pa lang ng opportunity, o naka-invest ka na?'],

  job_scam: [
  'Job scams ay dumarami sa Telegram at WhatsApp ngayon — yung "task" scams kung saan binibigyan ka muna ng maliit para magtiwala, tapos hihingian ka ng "deposit" para sa mas malaking task. Pagkatapos mong magbayad, mawawala sila.\n\nMga senyales: anumang upfront fee (training, registration, deposit), recruitment via random SMS o Telegram, magulong company info, hindi makatotohanang sahod (₱5,000/araw sa pag-like ng video — hindi totoo), pinipilit kang mag-recruit ng friends.\n\nLehitimong employer hindi humihingi ng bayad para magtrabaho ka. I-verify ang company sa DOLE (dole.gov.ph). Kung naloko ka na, magreport sa PNP-ACG sa (02) 8723-0401 local 7491.\n\nAno ang offer? Pwede kong tingnan ang mga red flags.'],

  identity_theft: [
  'Nakakastress yan, sorry. Mabilis natin ayusin:\n\nUnahin mo ang email password mo — yan ang master key, mareset ang lahat doon. Tapos ang banking, tapos ang social media. I-on ang 2FA sa lahat (mas mabuti ang authenticator app). Tawagan ang bangko at e-wallet provider mo para i-flag ang fraudulent activity at i-freeze ang cards kung kailangan.\n\nTapos magfile ng report sa PNP-ACG ((02) 8723-0401 local 7491) — magdala ng screenshots at valid ID. Kung naleak o nagamit ang personal data mo, pwede ring magfile sa National Privacy Commission sa privacy.gov.ph (RA 10173).\n\nAlam mo ba kung paano sila nakakuha ng access — phishing link, naleak na password, o iba pa?'],

  phishing_email: [
  'Mahirap kilalanin ang phishing email kasi mukhang totoo minsan. Ito ang i-check:\n\n• Buong email address ng sender (hindi lang yung name) — madalas ginagaya ang domain ("bdo-secure@gmial.com" sa halip na totoo).\n• "Dear Customer" sa halip na pangalan mo — generic greeting = red flag.\n• Nagmamadaling threat ("account na-lock na", "mawawala na ang access").\n• Hover (huwag pindutin) ang links para makita kung saan talaga papunta.\n\nKung suspicious, huwag pindutin ang anumang link sa email. Bukas ka ng bagong tab at pumunta mismo sa opisyal na website. Pwede ring i-forward ang email sa report@cert.gov.ph — iniimbestigahan ng DICT yan.\n\nMay specific na email ka ba? Pwede kong tulungan mong basahin ang signs.',
  'Tingnan mo muna ang sender email address, hindi lang ang pangalan. Kung hindi ito galing sa opisyal na website ng kumpanya, scam yan. Huwag i-click ang anumang link. Gusto mo bang i-paste dito ang laman ng email?',
  'Ang mga pekeng email ay madalas nagbabanta na isasara ang account mo kung hindi ka kikilos agad. I-forward ang kahina-hinalang email sa report@cert.gov.ph. Ano ang sinasabi sa email na natanggap mo?']

};

function stableIndex(seed: string, max: number): number {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  return max > 0 ? h % max : 0;
}

export function pickResponse(intent: Intent, lang: 'en' | 'tl' = 'en', seed = ''): string {
  if (lang === 'tl' && responseVariantsTL[intent]) {
    const tlOptions = responseVariantsTL[intent];
    return tlOptions[stableIndex(seed + intent, tlOptions.length)];
  }
  const options = responseVariants[intent];
  return options[stableIndex(seed + intent, options.length)];
}
